// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Accordion: typeof import('./components/Accordion.vue')['default']
    Button: typeof import('./components/Button.vue')['default']
    CardEvent: typeof import('./components/Card/Event.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormAdvancedCalendar: typeof import('./components/Form/AdvancedCalendar.vue')['default']
    FormCalendar: typeof import('./components/Form/Calendar.vue')['default']
    FormCheckbox: typeof import('./components/Form/Checkbox.vue')['default']
    FormDatePicker: typeof import('./components/Form/DatePicker.vue')['default']
    FormInputGroup: typeof import('./components/Form/InputGroup.vue')['default']
    FormNumber: typeof import('./components/Form/Number.vue')['default']
    FormRadioButton: typeof import('./components/Form/RadioButton.vue')['default']
    FormRating: typeof import('./components/Form/Rating.vue')['default']
    FormSelect: typeof import('./components/Form/Select.vue')['default']
    FormSlider: typeof import('./components/Form/Slider.vue')['default']
    FormTextInput: typeof import('./components/Form/TextInput.vue')['default']
    GoogleMapMarker: typeof import('./components/GoogleMap/Marker.vue')['default']
    GoogleMapResults: typeof import('./components/GoogleMap/Results.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomeEvents: typeof import('./components/Home/Events.vue')['default']
    HomeHotels: typeof import('./components/Home/Hotels.vue')['default']
    HomeMain: typeof import('./components/Home/Main.vue')['default']
    LoaderItem: typeof import('./components/Loader/Item.vue')['default']
    LoaderPreloader: typeof import('./components/Loader/Preloader.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    MeilisearchInput: typeof import('./components/Meilisearch/Input.vue')['default']
    ModalCustom: typeof import('./components/Modal/Custom.vue')['default']
    ModalMessage: typeof import('./components/Modal/Message.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ResultsAmenitiesList: typeof import('./components/Results/AmenitiesList.vue')['default']
    ResultsCard: typeof import('./components/Results/Card.vue')['default']
    ResultsFilterList: typeof import('./components/Results/FilterList.vue')['default']
    ResultsFilterListItem: typeof import('./components/Results/FilterListItem.vue')['default']
    ResultsListView: typeof import('./components/Results/ListView.vue')['default']
    ResultsMapView: typeof import('./components/Results/MapView.vue')['default']
    ResultsRating: typeof import('./components/Results/Rating.vue')['default']
    ResultsTab: typeof import('./components/Results/Tab.vue')['default']
    RoomCard: typeof import('./components/Room/Card.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SideBar: typeof import('./components/SideBar.vue')['default']
    SwiperCard: typeof import('./components/Swiper/Card.vue')['default']
    SwiperImage: typeof import('./components/Swiper/Image.vue')['default']
    Toasts: typeof import('./components/Toasts/index.vue')['default']
    ToastsItem: typeof import('./components/Toasts/Item.vue')['default']
    TravellerDetails: typeof import('./components/TravellerDetails.vue')['default']
  }
}
