// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/Button.vue')['default']
    FormInputGroup: typeof import('./components/Form/InputGroup.vue')['default']
    FormTextInput: typeof import('./components/Form/TextInput.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LoaderItem: typeof import('./components/Loader/Item.vue')['default']
    LoaderPreloader: typeof import('./components/Loader/Preloader.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    ModalCustom: typeof import('./components/Modal/Custom.vue')['default']
    ModalMessage: typeof import('./components/Modal/Message.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
